import type { NextPage } from 'next'
import Head from 'next/head'


export default function Index() {
  const start = ["J'ai'", "Ma femme a", "Mon chien a"];
  const verbe = ["perdu", "mangé", "vendu"];
  const end = ["les documents", "le papier", "la signature", "la piscine"];
  const excuse = start[random(start.length)] + " / " + verbe[random(verbe.length)] + " / " + end[random(end.length)]

  return (
    <div className="container-xl">
      <Head>
        <title>Excuse moi, mais...</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <br />
        <br />
        <h1 className="text-center">Genarateur d’excuse</h1>
        <br />
        <br />
        <form action="" method="GET">
          <p>{excuse}, donc je ne peux pas t'augmenter.</p>
          <button type="submit">Btn</button>
        </form>
      </main>

      <footer>
        <br />
        <br />
        <p>Toi aussi,  aide ton employeur a trouver des excuses pour ne pas t’augmenter.</p>
      </footer>
    </div>
  )
}


function random(max: number) {
  return Math.floor(Math.random() * Math.floor(max));
}