import type { NextPage } from 'next'
import Head from 'next/head'


export default function Index() {
  const newLocal = Math.random()
  console.log(newLocal);
  return (
    <div className="container-xl">
      <Head>
        <title>Excuse moi, mais...</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <br />
        <br />
        <h1>
          Genarateur d’excuse
        </h1>
        <br />
        <br />
        <form action="" method="GET">
          <input type="text" value={newLocal} />
          <button type="submit">Btn</button>
        </form>
      </main>

      <footer>
        <br />
        <br />
        <p>Prend exemples sur ton employeur pour avoir plus d’excuses pour ne pas avoir d’augmentation.</p>
      </footer>
    </div>
  )
}
